messages:
  join: "§aVocê se conectou na sala SW-{room}"
  leave: "§cVocê saiu da partida de SkyWar!"
  unknown_command: "§cComando desconhecido! Tente /skywar help"
  incorrect_usage: "§cUso incorreto! Tente /skywar help"
  no_permission: "Você não tem permissão suficiente para executar esse comando."
  player_only: "Apenas jogadores podem usar esse comando."
  kit_selected: "§aVocê ativou o kit {kit}."
  kit_removed: "§cKit removido com sucesso."
  actual_kit: "§bSeu kit selecionado é o: {kit}."
  noactual_kit: "§cNenhum kit selecionado."
  error_arena: "§cVocê já está em uma arena."
  not_in_arena: "§cVocê não está em uma arena."
  join_arena: "§aVocê se juntou a sala SW-{arena}"
  leave_arena: "§cVocê saiu da arena."
  player_joined_arena: "§3[SkyWar] §6{player} se juntou a partida! ({X}/{Y})"
  player_leave_arena: "§3[SkyWar] §6{player} saiu da partida! ({X}/{Y})"
  seconds_to_start: "§3[SkyWar] §6Começando em §f{seconds} segundos§6!"
  game_start: "§3[SkyWar] §6Boa sorte! O jogo começou!"
  pvp_message: "§3[SkyWar] §6O PvP será liberado em {seconds} segundos!"
  winning_message: "§3[SkyWar] §6Parabéns! Você venceu o jogo!"
  game_finished: "§3[SkyWar] §6O jogo acabou! O vencedor foi: {player}"
  lobby_message: "§3[SkyWar] §6Vocês serão teleportados para o lobby em 15 segundos!"
  winner_message:
    - "§6Você ganhou §f{creditos} §6nessa partida:"
    - "   §f+20 §6por participação"
    - "   §f+100 §6pela vitória"
  messageDeath: "§3[SkyWar] §6{player} morreu! ({X}/{Y})"
  earningpoints: "§6+{points}"
  death: "§3[SkyWar] §6{player} caiu ({X}/{Y})"
  player_killed_oponent: "§3[SkyWar] §6{killer} eliminou {player}! ({X}/{Y})"
  first_blood_message: "§3[FirstBlood] §6{killer} eliminou {player}! ({X}/{Y})"
  extralifekit_message: "§3[SkyWar] §6{player} morreu porém estava utilizando o kit Vida Extra!"
  extralife_message_to_player: "§cVocê usou sua vida extra!"

  help:
    - "§6----- §3[SkyWar] &6-----"
    - "§6/skywar create <mapa> - Criação de mapas"
    - "§6/skywar remove <mapa> - Remoção de mapas"
    - "§6/start - Força o início da partida"
    - "§6/skywar help - Ajuda com o plugin"
    - "------------------"
